spring:
  application:
    name: arch-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/arch-demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # !! for development purpose only
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
